"""create hosted foundation schema

Revision ID: 3541c01e5fb2
Revises:
Create Date: 2026-09-23 20:45:28.012226
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "3541c01e5fb2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_organizations_actor_kind",
        ),
        sa.CheckConstraint(
            "state IN ('active', 'archived')", name="ck_organizations_state"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("identity_provider", sa.String(length=80), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "identity_provider", "provider_subject", name="uq_users_provider_subject"
        ),
    )
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_memberships_actor_kind",
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'operator', 'viewer')",
            name="ck_memberships_role",
        ),
        sa.CheckConstraint(
            "state IN ('invited', 'active', 'suspended', 'revoked')",
            name="ck_memberships_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_memberships_organization_user"
        ),
    )
    op.create_index(
        "ix_memberships_user_state",
        "organization_memberships",
        ["user_id", "state"],
        unique=False,
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_workspaces_actor_kind",
        ),
        sa.CheckConstraint(
            "state IN ('active', 'archived')", name="ck_workspaces_state"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "id", name="uq_workspaces_organization_id"
        ),
        sa.UniqueConstraint(
            "organization_id", "slug", name="uq_workspaces_organization_slug"
        ),
    )
    op.create_index(
        "ix_workspaces_organization_state",
        "workspaces",
        ["organization_id", "state"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("retention_policy_ref", sa.String(length=160), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_incident_id", sa.UUID(), nullable=True),
        sa.Column("correlation_triage_run_id", sa.UUID(), nullable=True),
        sa.Column("correlation_job_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_audit_events_actor_kind",
        ),
        sa.CheckConstraint(
            "classification IN ('public', 'internal', 'confidential', 'restricted')",
            name="ck_audit_events_classification",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_audit_events_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_organization_occurred",
        "audit_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_workspace_occurred",
        "audit_events",
        ["organization_id", "workspace_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("retention_policy_ref", sa.String(length=160), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_documents_actor_kind",
        ),
        sa.CheckConstraint(
            "category IN ('runbook', 'incident', 'log', 'knowledge', 'other')",
            name="ck_documents_category",
        ),
        sa.CheckConstraint(
            "classification IN ('public', 'internal', 'confidential', 'restricted')",
            name="ck_documents_classification",
        ),
        sa.CheckConstraint(
            "state IN ('pending_upload', 'available', 'failed', 'archived')",
            name="ck_documents_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_documents_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_documents_scope_id"
        ),
    )
    op.create_index(
        "ix_documents_scope_state",
        "documents",
        ["organization_id", "workspace_id", "state"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_provider", sa.String(length=80), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_external_id", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("retention_policy_ref", sa.String(length=160), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_incident_id", sa.UUID(), nullable=True),
        sa.Column("correlation_triage_run_id", sa.UUID(), nullable=True),
        sa.Column("correlation_job_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_incidents_actor_kind",
        ),
        sa.CheckConstraint(
            "classification IN ('public', 'internal', 'confidential', 'restricted')",
            name="ck_incidents_classification",
        ),
        sa.CheckConstraint(
            "state IN ('open', 'investigating', 'resolved', 'closed')",
            name="ck_incidents_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_incidents_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_incidents_scope_id"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "source_provider",
            "source_external_id",
            name="uq_incidents_source_external_id",
        ),
    )
    op.create_index(
        "ix_incidents_scope_created",
        "incidents",
        ["organization_id", "workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_incidents_scope_state",
        "incidents",
        ["organization_id", "workspace_id", "state"],
        unique=False,
    )
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_integrations_actor_kind",
        ),
        sa.CheckConstraint(
            "state IN ('active', 'disabled', 'error')", name="ck_integrations_state"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_integrations_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_integrations_scope_state",
        "integrations",
        ["organization_id", "workspace_id", "state"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("subject_type", sa.String(length=80), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_incident_id", sa.UUID(), nullable=True),
        sa.Column("correlation_triage_run_id", sa.UUID(), nullable=True),
        sa.Column("correlation_job_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_jobs_actor_kind",
        ),
        sa.CheckConstraint(
            "kind IN ('triage', 'index_build', 'context_collection', 'action_execution')",
            name="ck_jobs_kind",
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_jobs_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_jobs_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_jobs_scope_state_created",
        "jobs",
        ["organization_id", "workspace_id", "state", "created_at"],
        unique=False,
    )
    op.create_table(
        "knowledge_index_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_index_versions_actor_kind",
        ),
        sa.CheckConstraint(
            "state IN ('building', 'active', 'failed', 'inactive')",
            name="ck_index_versions_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_index_versions_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_index_versions_scope_id"
        ),
    )
    op.create_index(
        "ix_index_versions_scope_state",
        "knowledge_index_versions",
        ["organization_id", "workspace_id", "state"],
        unique=False,
    )
    op.create_index(
        "uq_index_versions_one_active",
        "knowledge_index_versions",
        ["organization_id", "workspace_id"],
        unique=True,
        postgresql_where=sa.text("state = 'active'"),
    )
    op.create_table(
        "usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("retention_policy_ref", sa.String(length=160), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_incident_id", sa.UUID(), nullable=True),
        sa.Column("correlation_triage_run_id", sa.UUID(), nullable=True),
        sa.Column("correlation_job_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "actor_kind IS NULL OR actor_kind IN ('human', 'service_account', 'system')",
            name="ck_usage_events_actor_kind",
        ),
        sa.CheckConstraint("quantity >= 0", name="ck_usage_events_quantity"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_usage_events_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "idempotency_key",
            name="uq_usage_events_idempotency",
        ),
    )
    op.create_index(
        "ix_usage_events_scope_occurred",
        "usage_events",
        ["organization_id", "workspace_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_document_versions_actor_kind",
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_document_versions_size"),
        sa.CheckConstraint("version_number > 0", name="ck_document_versions_number"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "document_id"],
            ["documents.organization_id", "documents.workspace_id", "documents.id"],
            name="fk_document_versions_document_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_document_versions_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "version_number", name="uq_document_versions_number"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "id",
            name="uq_document_versions_scope_id",
        ),
    )
    op.create_index(
        "ix_document_versions_document",
        "document_versions",
        ["document_id", "version_number"],
        unique=False,
    )
    op.create_table(
        "triage_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("retention_policy_ref", sa.String(length=160), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_incident_id", sa.UUID(), nullable=True),
        sa.Column("correlation_triage_run_id", sa.UUID(), nullable=True),
        sa.Column("correlation_job_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_triage_runs_actor_kind",
        ),
        sa.CheckConstraint(
            "classification IN ('public', 'internal', 'confidential', 'restricted')",
            name="ck_triage_runs_classification",
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_triage_runs_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "incident_id"],
            ["incidents.organization_id", "incidents.workspace_id", "incidents.id"],
            name="fk_triage_runs_incident_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_triage_runs_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_triage_runs_scope_id"
        ),
    )
    op.create_index(
        "ix_triage_runs_incident_created",
        "triage_runs",
        ["incident_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_triage_runs_scope_state",
        "triage_runs",
        ["organization_id", "workspace_id", "state"],
        unique=False,
    )
    op.create_table(
        "action_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=120), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("risk", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("triage_run_id", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome_reference", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_system_name", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('human', 'service_account', 'system')",
            name="ck_actions_actor_kind",
        ),
        sa.CheckConstraint(
            "risk IN ('informational', 'consequential')", name="ck_actions_risk"
        ),
        sa.CheckConstraint(
            "state IN ('proposed', 'awaiting_approval', 'ready', 'executing', 'succeeded', 'failed', 'rejected', 'expired', 'cancelled')",
            name="ck_actions_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "incident_id"],
            ["incidents.organization_id", "incidents.workspace_id", "incidents.id"],
            name="fk_actions_incident_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "triage_run_id"],
            [
                "triage_runs.organization_id",
                "triage_runs.workspace_id",
                "triage_runs.id",
            ],
            name="fk_actions_triage_run_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_actions_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_actions_scope_id"
        ),
    )
    op.create_index(
        "ix_actions_scope_state",
        "action_proposals",
        ["organization_id", "workspace_id", "state"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("triage_run_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("retention_policy_ref", sa.String(length=160), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "classification IN ('public', 'internal', 'confidential', 'restricted')",
            name="ck_evidence_classification",
        ),
        sa.CheckConstraint(
            "type IN ('log', 'incident', 'runbook', 'knowledge', 'decision', 'metric', 'alert', 'other')",
            name="ck_evidence_type",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "triage_run_id"],
            [
                "triage_runs.organization_id",
                "triage_runs.workspace_id",
                "triage_runs.id",
            ],
            name="fk_evidence_triage_run_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_evidence_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_evidence_triage_run",
        "evidence",
        ["triage_run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("triage_run_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by_kind", sa.String(length=32), nullable=False),
        sa.Column("submitted_by_id", sa.UUID(), nullable=True),
        sa.Column("submitted_by_system_name", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("diagnosis_correct", sa.Boolean(), nullable=True),
        sa.Column("actions_useful", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("retention_policy_ref", sa.String(length=160), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "classification IN ('public', 'internal', 'confidential', 'restricted')",
            name="ck_feedback_classification",
        ),
        sa.CheckConstraint(
            "submitted_by_kind IN ('human', 'service_account', 'system')",
            name="ck_feedback_actor_kind",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "triage_run_id"],
            [
                "triage_runs.organization_id",
                "triage_runs.workspace_id",
                "triage_runs.id",
            ],
            name="fk_feedback_triage_run_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_feedback_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feedback_triage_run_created",
        "feedback",
        ["triage_run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "knowledge_index_documents",
        sa.Column("index_version_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "document_version_id"],
            [
                "document_versions.organization_id",
                "document_versions.workspace_id",
                "document_versions.id",
            ],
            name="fk_index_documents_document_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "index_version_id"],
            [
                "knowledge_index_versions.organization_id",
                "knowledge_index_versions.workspace_id",
                "knowledge_index_versions.id",
            ],
            name="fk_index_documents_index_scope",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("index_version_id", "document_version_id"),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("requested_by_kind", sa.String(length=32), nullable=False),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_system_name", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by_kind", sa.String(length=32), nullable=True),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_by_system_name", sa.String(length=120), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "decided_by_kind IS NULL OR decided_by_kind IN ('human', 'service_account', 'system')",
            name="ck_approvals_decided_actor_kind",
        ),
        sa.CheckConstraint(
            "requested_by_kind IN ('human', 'service_account', 'system')",
            name="ck_approvals_requested_actor_kind",
        ),
        sa.CheckConstraint(
            "state IN ('requested', 'approved', 'rejected', 'expired', 'cancelled')",
            name="ck_approvals_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "action_id"],
            [
                "action_proposals.organization_id",
                "action_proposals.workspace_id",
                "action_proposals.id",
            ],
            name="fk_approvals_action_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name="fk_approvals_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_approvals_action_state", "approvals", ["action_id", "state"], unique=False
    )
    # ### end Alembic commands ###

    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aira_app') THEN
            RAISE EXCEPTION 'Required runtime role aira_app does not exist';
          END IF;
        END
        $$
        """
    )

    organization_policies = {
        "organizations": "id",
        "organization_memberships": "organization_id",
        "workspaces": "organization_id",
    }
    workspace_tables = (
        "incidents",
        "triage_runs",
        "evidence",
        "feedback",
        "documents",
        "document_versions",
        "knowledge_index_versions",
        "knowledge_index_documents",
        "integrations",
        "jobs",
        "action_proposals",
        "approvals",
        "usage_events",
    )
    organization_setting = (
        "NULLIF(current_setting('app.organization_id', true), '')::uuid"
    )
    workspace_setting = "NULLIF(current_setting('app.workspace_id', true), '')::uuid"

    for table_name, organization_column in organization_policies.items():
        expression = f"{organization_column} = {organization_setting}"
        op.execute(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table_name}" '
            f"USING ({expression}) WITH CHECK ({expression})"
        )

    for table_name in workspace_tables:
        expression = (
            f"organization_id = {organization_setting} "
            f"AND workspace_id = {workspace_setting}"
        )
        op.execute(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table_name}" '
            f"USING ({expression}) WITH CHECK ({expression})"
        )

    audit_expression = (
        f"organization_id = {organization_setting} AND "
        f"(workspace_id IS NULL OR workspace_id = {workspace_setting})"
    )
    op.execute('ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE "audit_events" FORCE ROW LEVEL SECURITY')
    op.execute(
        'CREATE POLICY tenant_isolation ON "audit_events" '
        f"USING ({audit_expression}) WITH CHECK ({audit_expression})"
    )

    op.execute("REVOKE CREATE ON SCHEMA public FROM aira_app")
    op.execute("GRANT USAGE ON SCHEMA public TO aira_app")
    op.execute("REVOKE ALL PRIVILEGES ON TABLE alembic_version FROM aira_app")
    application_tables = (
        "users",
        *organization_policies,
        *workspace_tables,
        "audit_events",
    )
    for table_name in application_tables:
        op.execute(
            f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "{table_name}" TO aira_app'
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_approvals_action_state", table_name="approvals")
    op.drop_table("approvals")
    op.drop_table("knowledge_index_documents")
    op.drop_index("ix_feedback_triage_run_created", table_name="feedback")
    op.drop_table("feedback")
    op.drop_index("ix_evidence_triage_run", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index("ix_actions_scope_state", table_name="action_proposals")
    op.drop_table("action_proposals")
    op.drop_index("ix_triage_runs_scope_state", table_name="triage_runs")
    op.drop_index("ix_triage_runs_incident_created", table_name="triage_runs")
    op.drop_table("triage_runs")
    op.drop_index("ix_document_versions_document", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index("ix_usage_events_scope_occurred", table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(
        "uq_index_versions_one_active",
        table_name="knowledge_index_versions",
        postgresql_where=sa.text("state = 'active'"),
    )
    op.drop_index(
        "ix_index_versions_scope_state", table_name="knowledge_index_versions"
    )
    op.drop_table("knowledge_index_versions")
    op.drop_index("ix_jobs_scope_state_created", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_integrations_scope_state", table_name="integrations")
    op.drop_table("integrations")
    op.drop_index("ix_incidents_scope_state", table_name="incidents")
    op.drop_index("ix_incidents_scope_created", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_documents_scope_state", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_audit_events_workspace_occurred", table_name="audit_events")
    op.drop_index("ix_audit_events_organization_occurred", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_workspaces_organization_state", table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index("ix_memberships_user_state", table_name="organization_memberships")
    op.drop_table("organization_memberships")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
